//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP41CV {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HP41CV.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string AboutCommand {
            get {
                return ResourceManager.GetString("AboutCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activ ähnelt.
        /// </summary>
        internal static string Activ {
            get {
                return ResourceManager.GetString("Activ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HP-41CV ähnelt.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Layout ähnelt.
        /// </summary>
        internal static string ButtonLoadLayout {
            get {
                return ResourceManager.GetString("ButtonLoadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Program ähnelt.
        /// </summary>
        internal static string ButtonLoadProgram {
            get {
                return ResourceManager.GetString("ButtonLoadProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Layout ähnelt.
        /// </summary>
        internal static string ButtonSaveLayout {
            get {
                return ResourceManager.GetString("ButtonSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Program ähnelt.
        /// </summary>
        internal static string ButtonSaveProgram {
            get {
                return ResourceManager.GetString("ButtonSaveProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy for {0} ähnelt.
        /// </summary>
        internal static string BuyButton {
            get {
                return ResourceManager.GetString("BuyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the number and press the Function Key. ähnelt.
        /// </summary>
        internal static string Chapter1Description {
            get {
                return ResourceManager.GetString("Chapter1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die    Example  1/25=0.04 ähnelt.
        /// </summary>
        internal static string Chapter1Example1 {
            get {
                return ResourceManager.GetString("Chapter1Example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die    Example  sin(45)=0.7071 ähnelt.
        /// </summary>
        internal static string Chapter1Example2 {
            get {
                return ResourceManager.GetString("Chapter1Example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Chapter1Remark {
            get {
                return ResourceManager.GetString("Chapter1Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Function with one Variable ähnelt.
        /// </summary>
        internal static string Chapter1Title {
            get {
                return ResourceManager.GetString("Chapter1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter both numbers and press the Function Key. ähnelt.
        /// </summary>
        internal static string Chapter2Description {
            get {
                return ResourceManager.GetString("Chapter2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die    Example  15+7=22 ähnelt.
        /// </summary>
        internal static string Chapter2Example1 {
            get {
                return ResourceManager.GetString("Chapter2Example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die    Example  4³ = 64 ähnelt.
        /// </summary>
        internal static string Chapter2Example2 {
            get {
                return ResourceManager.GetString("Chapter2Example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Chapter2Remark {
            get {
                return ResourceManager.GetString("Chapter2Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Function with two Variables ähnelt.
        /// </summary>
        internal static string Chapter2Title {
            get {
                return ResourceManager.GetString("Chapter2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start with the inner bracket and leave intermediate data on the stack.  ähnelt.
        /// </summary>
        internal static string Chapter3Description {
            get {
                return ResourceManager.GetString("Chapter3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   Example (5+7)*(3-1) = 24 ähnelt.
        /// </summary>
        internal static string Chapter3Example {
            get {
                return ResourceManager.GetString("Chapter3Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continued calculation ähnelt.
        /// </summary>
        internal static string Chapter3Title {
            get {
                return ResourceManager.GetString("Chapter3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for Android ähnelt.
        /// </summary>
        internal static string ForD {
            get {
                return ResourceManager.GetString("ForD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for iOS ähnelt.
        /// </summary>
        internal static string ForI {
            get {
                return ResourceManager.GetString("ForI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for Windows ähnelt.
        /// </summary>
        internal static string ForW {
            get {
                return ResourceManager.GetString("ForW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter one or two operator and select the function ähnelt.
        /// </summary>
        internal static string Function1Description {
            get {
                return ResourceManager.GetString("Function1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arithmetic functions ähnelt.
        /// </summary>
        internal static string Function1Title {
            get {
                return ResourceManager.GetString("Function1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The angle for the trigonometric function can be specified in degree, radian or centesimal degree ähnelt.
        /// </summary>
        internal static string Function2Description {
            get {
                return ResourceManager.GetString("Function2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trigonometric function ähnelt.
        /// </summary>
        internal static string Function2Title {
            get {
                return ResourceManager.GetString("Function2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Function3Description {
            get {
                return ResourceManager.GetString("Function3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logarithmic and exponential function ähnelt.
        /// </summary>
        internal static string Function3Title {
            get {
                return ResourceManager.GetString("Function3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use for branches in programs or just show the result ähnelt.
        /// </summary>
        internal static string Function4Description {
            get {
                return ResourceManager.GetString("Function4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logical function ähnelt.
        /// </summary>
        internal static string Function4Title {
            get {
                return ResourceManager.GetString("Function4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einter Values from X and Y regiser or find the results there ähnelt.
        /// </summary>
        internal static string Function5Description {
            get {
                return ResourceManager.GetString("Function5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistic function (optional) ähnelt.
        /// </summary>
        internal static string Function5Title {
            get {
                return ResourceManager.GetString("Function5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a general register via its two digit number or select a stack register by entering a . followed by the letter of an stack register (X,Y,Z,T or L) ähnelt.
        /// </summary>
        internal static string Function6Description {
            get {
                return ResourceManager.GetString("Function6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register function ähnelt.
        /// </summary>
        internal static string Function6Title {
            get {
                return ResourceManager.GetString("Function6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Flags for branches in programs or to control the behavior of the calculator ähnelt.
        /// </summary>
        internal static string Function7Description {
            get {
                return ResourceManager.GetString("Function7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flag function ähnelt.
        /// </summary>
        internal static string Function7Title {
            get {
                return ResourceManager.GetString("Function7Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Function8Description {
            get {
                return ResourceManager.GetString("Function8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conversion function ähnelt.
        /// </summary>
        internal static string Function8Title {
            get {
                return ResourceManager.GetString("Function8Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the format and enter the number of after decimal digits or the number of bytes ähnelt.
        /// </summary>
        internal static string Function9Description {
            get {
                return ResourceManager.GetString("Function9Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number format ähnelt.
        /// </summary>
        internal static string Function9Title {
            get {
                return ResourceManager.GetString("Function9Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main functions ähnelt.
        /// </summary>
        internal static string FunctionTitle {
            get {
                return ResourceManager.GetString("FunctionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Antilogarithm (common) ähnelt.
        /// </summary>
        internal static string Help10PX {
            get {
                return ResourceManager.GetString("Help10PX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reciprocal ähnelt.
        /// </summary>
        internal static string Help1D {
            get {
                return ResourceManager.GetString("Help1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Absolute value ähnelt.
        /// </summary>
        internal static string HelpAbs {
            get {
                return ResourceManager.GetString("HelpAbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arc cosine ähnelt.
        /// </summary>
        internal static string HelpACOS {
            get {
                return ResourceManager.GetString("HelpACOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add x and y  ähnelt.
        /// </summary>
        internal static string HelpAdd {
            get {
                return ResourceManager.GetString("HelpAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ALPHA mode off ähnelt.
        /// </summary>
        internal static string HelpAOFF {
            get {
                return ResourceManager.GetString("HelpAOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ALPHA mode on ähnelt.
        /// </summary>
        internal static string HelpAON {
            get {
                return ResourceManager.GetString("HelpAON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Append ALPHA display ähnelt.
        /// </summary>
        internal static string HelpAPPEND {
            get {
                return ResourceManager.GetString("HelpAPPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ALPHA recall ähnelt.
        /// </summary>
        internal static string HelpARCL {
            get {
                return ResourceManager.GetString("HelpARCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ALPHA shift left ähnelt.
        /// </summary>
        internal static string HelpASHF {
            get {
                return ResourceManager.GetString("HelpASHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arc sine ähnelt.
        /// </summary>
        internal static string HelpASIN {
            get {
                return ResourceManager.GetString("HelpASIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assing a function to a Key ähnelt.
        /// </summary>
        internal static string HelpASN {
            get {
                return ResourceManager.GetString("HelpASN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ALPHA store ähnelt.
        /// </summary>
        internal static string HelpASTO {
            get {
                return ResourceManager.GetString("HelpASTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arc tangent ähnelt.
        /// </summary>
        internal static string HelpATAN {
            get {
                return ResourceManager.GetString("HelpATAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advance paper ähnelt.
        /// </summary>
        internal static string HelpAVD {
            get {
                return ResourceManager.GetString("HelpAVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ALPHA view ähnelt.
        /// </summary>
        internal static string HelpAVIEW {
            get {
                return ResourceManager.GetString("HelpAVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear last entered digit ähnelt.
        /// </summary>
        internal static string HelpBACK {
            get {
                return ResourceManager.GetString("HelpBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beeper ähnelt.
        /// </summary>
        internal static string HelpBEEP {
            get {
                return ResourceManager.GetString("HelpBEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Binary display ähnelt.
        /// </summary>
        internal static string HelpBIN {
            get {
                return ResourceManager.GetString("HelpBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back step ähnelt.
        /// </summary>
        internal static string HelpBST {
            get {
                return ResourceManager.GetString("HelpBST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Catalog list of  ähnelt.
        /// </summary>
        internal static string HelpCAT {
            get {
                return ResourceManager.GetString("HelpCAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change sign ähnelt.
        /// </summary>
        internal static string HelpCHS {
            get {
                return ResourceManager.GetString("HelpCHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ALPHA register ähnelt.
        /// </summary>
        internal static string HelpCLA {
            get {
                return ResourceManager.GetString("HelpCLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear alpha register ähnelt.
        /// </summary>
        internal static string HelpClearA {
            get {
                return ResourceManager.GetString("HelpClearA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear flag ähnelt.
        /// </summary>
        internal static string HelpClearFlag {
            get {
                return ResourceManager.GetString("HelpClearFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear program ähnelt.
        /// </summary>
        internal static string HelpClearProgram {
            get {
                return ResourceManager.GetString("HelpClearProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear all stack register ähnelt.
        /// </summary>
        internal static string HelpClearStack {
            get {
                return ResourceManager.GetString("HelpClearStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear x register ähnelt.
        /// </summary>
        internal static string HelpClearX {
            get {
                return ResourceManager.GetString("HelpClearX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear all storage registers ähnelt.
        /// </summary>
        internal static string HelpCLRG {
            get {
                return ResourceManager.GetString("HelpCLRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die binomial coefficient ähnelt.
        /// </summary>
        internal static string HelpCNK {
            get {
                return ResourceManager.GetString("HelpCNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cosine ähnelt.
        /// </summary>
        internal static string HelpCOS {
            get {
                return ResourceManager.GetString("HelpCOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Octal to decimal conversion ähnelt.
        /// </summary>
        internal static string HelpDEC {
            get {
                return ResourceManager.GetString("HelpDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Degrees mode ähnelt.
        /// </summary>
        internal static string HelpDEG {
            get {
                return ResourceManager.GetString("HelpDEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intern the datatype double is used ähnelt.
        /// </summary>
        internal static string HelpDifferents {
            get {
                return ResourceManager.GetString("HelpDifferents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All register can contain numbers and text simultaneously ähnelt.
        /// </summary>
        internal static string HelpDifferents1 {
            get {
                return ResourceManager.GetString("HelpDifferents1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Divide y by x ähnelt.
        /// </summary>
        internal static string HelpDiv {
            get {
                return ResourceManager.GetString("HelpDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrement and skip if equal (Programming option) ähnelt.
        /// </summary>
        internal static string HelpDSE {
            get {
                return ResourceManager.GetString("HelpDSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Degrees to radians conversion ähnelt.
        /// </summary>
        internal static string HelpDTR {
            get {
                return ResourceManager.GetString("HelpDTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter exponent ähnelt.
        /// </summary>
        internal static string HelpEEX {
            get {
                return ResourceManager.GetString("HelpEEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End of program (Programming option) ähnelt.
        /// </summary>
        internal static string HelpEND {
            get {
                return ResourceManager.GetString("HelpEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engineering notation display ähnelt.
        /// </summary>
        internal static string HelpENG {
            get {
                return ResourceManager.GetString("HelpENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter number in X-register into Y-register ähnelt.
        /// </summary>
        internal static string HelpENTER {
            get {
                return ResourceManager.GetString("HelpENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Antilogarithm (natural) ähnelt.
        /// </summary>
        internal static string HelpEPX {
            get {
                return ResourceManager.GetString("HelpEPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Antilogarithm (natural) for arguments close to zero ähnelt.
        /// </summary>
        internal static string HelpEPX1 {
            get {
                return ResourceManager.GetString("HelpEPX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extention functions ähnelt.
        /// </summary>
        internal static string HelpExtention {
            get {
                return ResourceManager.GetString("HelpExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Factorial ähnelt.
        /// </summary>
        internal static string HelpFACT {
            get {
                return ResourceManager.GetString("HelpFACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ‘‘Flag clear’’ test ähnelt.
        /// </summary>
        internal static string HelpFC {
            get {
                return ResourceManager.GetString("HelpFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ‘‘Flag clear’’ test and clear ähnelt.
        /// </summary>
        internal static string HelpFCC {
            get {
                return ResourceManager.GetString("HelpFCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fixed point display ähnelt.
        /// </summary>
        internal static string HelpFIX {
            get {
                return ResourceManager.GetString("HelpFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fractional portion of number ähnelt.
        /// </summary>
        internal static string HelpFRC {
            get {
                return ResourceManager.GetString("HelpFRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ‘‘Flag set’’ test. ähnelt.
        /// </summary>
        internal static string HelpFS {
            get {
                return ResourceManager.GetString("HelpFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ‘‘Flag set’’ test and clear ähnelt.
        /// </summary>
        internal static string HelpFSC {
            get {
                return ResourceManager.GetString("HelpFSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grads mode ähnelt.
        /// </summary>
        internal static string HelpGRAD {
            get {
                return ResourceManager.GetString("HelpGRAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hexadecimal display ähnelt.
        /// </summary>
        internal static string HelpHEX {
            get {
                return ResourceManager.GetString("HelpHEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours (decimal) to hours minutes, seconds conversion ähnelt.
        /// </summary>
        internal static string HelpHMS {
            get {
                return ResourceManager.GetString("HelpHMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours, minutes, seconds subtraction ähnelt.
        /// </summary>
        internal static string HelpHMSM {
            get {
                return ResourceManager.GetString("HelpHMSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours, minutes, seconds addition ähnelt.
        /// </summary>
        internal static string HelpHMSP {
            get {
                return ResourceManager.GetString("HelpHMSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours, minutes, seconds to decimal hours conversion ähnelt.
        /// </summary>
        internal static string HelpHR {
            get {
                return ResourceManager.GetString("HelpHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Integer portion of number ähnelt.
        /// </summary>
        internal static string HelpINT {
            get {
                return ResourceManager.GetString("HelpINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increment and skip if greater ähnelt.
        /// </summary>
        internal static string HelpISG {
            get {
                return ResourceManager.GetString("HelpISG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LAST X register recall ähnelt.
        /// </summary>
        internal static string HelpLASTX {
            get {
                return ResourceManager.GetString("HelpLASTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logarithm (natural) ähnelt.
        /// </summary>
        internal static string HelpLN {
            get {
                return ResourceManager.GetString("HelpLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logarithm (natural for arguments close to one) ähnelt.
        /// </summary>
        internal static string HelpLN1 {
            get {
                return ResourceManager.GetString("HelpLN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logarithm (common) ähnelt.
        /// </summary>
        internal static string HelpLOG {
            get {
                return ResourceManager.GetString("HelpLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mean (Statistic option) ähnelt.
        /// </summary>
        internal static string HelpMEAN {
            get {
                return ResourceManager.GetString("HelpMEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modulo (remainder) ähnelt.
        /// </summary>
        internal static string HelpMOD {
            get {
                return ResourceManager.GetString("HelpMOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiply x and y  ähnelt.
        /// </summary>
        internal static string HelpMul {
            get {
                return ResourceManager.GetString("HelpMul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decimal to Octal conversion ähnelt.
        /// </summary>
        internal static string HelpOCT {
            get {
                return ResourceManager.GetString("HelpOCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Power off ähnelt.
        /// </summary>
        internal static string HelpOFF {
            get {
                return ResourceManager.GetString("HelpOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Percent ähnelt.
        /// </summary>
        internal static string HelpPer {
            get {
                return ResourceManager.GetString("HelpPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Percent of change ähnelt.
        /// </summary>
        internal static string HelpPerC {
            get {
                return ResourceManager.GetString("HelpPerC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pi ähnelt.
        /// </summary>
        internal static string HelpPI {
            get {
                return ResourceManager.GetString("HelpPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programs can be load from text files with the extension 41p ähnelt.
        /// </summary>
        internal static string HelpProgramming {
            get {
                return ResourceManager.GetString("HelpProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build in function loops and branches can be used ähnelt.
        /// </summary>
        internal static string HelpProgramming1 {
            get {
                return ResourceManager.GetString("HelpProgramming1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not supported is the edit functionality ähnelt.
        /// </summary>
        internal static string HelpProgramming2 {
            get {
                return ResourceManager.GetString("HelpProgramming2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple Example ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample1 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program=CIRCLE ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample1Code1 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample1Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X↑2 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample1Code2 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample1Code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PI ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample1Code3 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample1Code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die * ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample1Code4 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample1Code4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EndProgram ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample1Code5 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample1Code5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate the area of a circle ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample1Description {
            get {
                return ResourceManager.GetString("HelpProgrammingExample1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die program name ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample1Remark1 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample1Remark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program with loop ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program=INTEREST ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code1 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STO 00 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code10 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LBL 01 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code11 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RCL 02 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code12 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RCL 01 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code13 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code14 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ST+ 02 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code15 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DSE 00 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code16 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GTO 01 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code17 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RCL 02 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code18 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EndProgram ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code19 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ᵀINTEREST? ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code2 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PROMPT ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code3 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STO 01 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code4 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ᵀCAPITAL? ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code5 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PROMPT ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code6 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STO 02 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code7 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ᵀYEARS? ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code8 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PROMPT ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Code9 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Code9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die calculation of compount interest ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Description {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die program name ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark1 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and store it as counter in registe 0 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark10 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die lable for the loop ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark11 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die decease the counter ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark16 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and jump to the lable as long as the count has not reached zero ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark17 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show the result ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark18 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die request the interest ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark3 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and store it in register 1 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark4 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die request the captal ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark6 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and store it in register 2 ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark7 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die request the runtime ähnelt.
        /// </summary>
        internal static string HelpProgrammingExample2Remark9 {
            get {
                return ResourceManager.GetString("HelpProgrammingExample2Remark9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prompt ähnelt.
        /// </summary>
        internal static string HelpPROMPT {
            get {
                return ResourceManager.GetString("HelpPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause (Programming option) ähnelt.
        /// </summary>
        internal static string HelpPSE {
            get {
                return ResourceManager.GetString("HelpPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polar to rectangular conversion ähnelt.
        /// </summary>
        internal static string HelpPTR {
            get {
                return ResourceManager.GetString("HelpPTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radians mode ähnelt.
        /// </summary>
        internal static string HelpRAD {
            get {
                return ResourceManager.GetString("HelpRAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recall ähnelt.
        /// </summary>
        internal static string HelpRCL {
            get {
                return ResourceManager.GetString("HelpRCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roll down ähnelt.
        /// </summary>
        internal static string HelpRD {
            get {
                return ResourceManager.GetString("HelpRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Round ähnelt.
        /// </summary>
        internal static string HelpRND {
            get {
                return ResourceManager.GetString("HelpRND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run/stop. Stops program (Programming option) ähnelt.
        /// </summary>
        internal static string HelpRS {
            get {
                return ResourceManager.GetString("HelpRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radians to degrees conversion ähnelt.
        /// </summary>
        internal static string HelpRTD {
            get {
                return ResourceManager.GetString("HelpRTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rectangular to polar conversion ähnelt.
        /// </summary>
        internal static string HelpRTP {
            get {
                return ResourceManager.GetString("HelpRTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roll up ähnelt.
        /// </summary>
        internal static string HelpRU {
            get {
                return ResourceManager.GetString("HelpRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scientific notation display ähnelt.
        /// </summary>
        internal static string HelpSCI {
            get {
                return ResourceManager.GetString("HelpSCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard deviation (Statistic option) ähnelt.
        /// </summary>
        internal static string HelpSDEV {
            get {
                return ResourceManager.GetString("HelpSDEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set program flag ähnelt.
        /// </summary>
        internal static string HelpSF {
            get {
                return ResourceManager.GetString("HelpSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign, unary of x ähnelt.
        /// </summary>
        internal static string HelpSIGN {
            get {
                return ResourceManager.GetString("HelpSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sine ähnelt.
        /// </summary>
        internal static string HelpSIN {
            get {
                return ResourceManager.GetString("HelpSIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size of register configuration ähnelt.
        /// </summary>
        internal static string HelpSIZE {
            get {
                return ResourceManager.GetString("HelpSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Square root ähnelt.
        /// </summary>
        internal static string HelpSQRT {
            get {
                return ResourceManager.GetString("HelpSQRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single step ähnelt.
        /// </summary>
        internal static string HelpSST {
            get {
                return ResourceManager.GetString("HelpSST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard functions ähnelt.
        /// </summary>
        internal static string HelpStandard {
            get {
                return ResourceManager.GetString("HelpStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add x and y to statistic register (Statistic option) ähnelt.
        /// </summary>
        internal static string HelpStatAdd {
            get {
                return ResourceManager.GetString("HelpStatAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear statistic register (Statistic option) ähnelt.
        /// </summary>
        internal static string HelpStatClear {
            get {
                return ResourceManager.GetString("HelpStatClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove x and y from statistic register (Statistic option) ähnelt.
        /// </summary>
        internal static string HelpStatRemove {
            get {
                return ResourceManager.GetString("HelpStatRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage register division ähnelt.
        /// </summary>
        internal static string HelpSTD {
            get {
                return ResourceManager.GetString("HelpSTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage register multiplication ähnelt.
        /// </summary>
        internal static string HelpSTM {
            get {
                return ResourceManager.GetString("HelpSTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Store ähnelt.
        /// </summary>
        internal static string HelpSTO {
            get {
                return ResourceManager.GetString("HelpSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop. In program, stops execution ähnelt.
        /// </summary>
        internal static string HelpSTOP {
            get {
                return ResourceManager.GetString("HelpSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage register addition ähnelt.
        /// </summary>
        internal static string HelpSTP {
            get {
                return ResourceManager.GetString("HelpSTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage register substraction ähnelt.
        /// </summary>
        internal static string HelpSTS {
            get {
                return ResourceManager.GetString("HelpSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die substract x from y  ähnelt.
        /// </summary>
        internal static string HelpSub {
            get {
                return ResourceManager.GetString("HelpSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tangent ähnelt.
        /// </summary>
        internal static string HelpTAN {
            get {
                return ResourceManager.GetString("HelpTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HP-41CV Help ähnelt.
        /// </summary>
        internal static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tone of beeper ähnelt.
        /// </summary>
        internal static string HelpTONE {
            get {
                return ResourceManager.GetString("HelpTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View register contens ähnelt.
        /// </summary>
        internal static string HelpVIEW {
            get {
                return ResourceManager.GetString("HelpVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Square ähnelt.
        /// </summary>
        internal static string HelpX2 {
            get {
                return ResourceManager.GetString("HelpX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X equal to 0 conditional test ähnelt.
        /// </summary>
        internal static string HelpXEN {
            get {
                return ResourceManager.GetString("HelpXEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute a program or function ähnelt.
        /// </summary>
        internal static string HelpXEQ {
            get {
                return ResourceManager.GetString("HelpXEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X equal Y conditional test ähnelt.
        /// </summary>
        internal static string HelpXEY {
            get {
                return ResourceManager.GetString("HelpXEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X greater then 0 conditional test ähnelt.
        /// </summary>
        internal static string HelpXGN {
            get {
                return ResourceManager.GetString("HelpXGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X greater then Y conditional test ähnelt.
        /// </summary>
        internal static string HelpXGY {
            get {
                return ResourceManager.GetString("HelpXGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X less then or equal to 0 conditional test ähnelt.
        /// </summary>
        internal static string HelpXLEN {
            get {
                return ResourceManager.GetString("HelpXLEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X less then or equal to Y conditional test ähnelt.
        /// </summary>
        internal static string HelpXLEY {
            get {
                return ResourceManager.GetString("HelpXLEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X less then Y conditional test ähnelt.
        /// </summary>
        internal static string HelpXLY {
            get {
                return ResourceManager.GetString("HelpXLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string HelpXROM {
            get {
                return ResourceManager.GetString("HelpXROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exchange X- and Y-registers ähnelt.
        /// </summary>
        internal static string HelpXTY {
            get {
                return ResourceManager.GetString("HelpXTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X not equal to 0 conditional test ähnelt.
        /// </summary>
        internal static string HelpXUN {
            get {
                return ResourceManager.GetString("HelpXUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X not equal to Y conditional test ähnelt.
        /// </summary>
        internal static string HelpXUY {
            get {
                return ResourceManager.GetString("HelpXUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exponential ähnelt.
        /// </summary>
        internal static string HelpYPX {
            get {
                return ResourceManager.GetString("HelpYPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die in peparation ähnelt.
        /// </summary>
        internal static string InPreparation {
            get {
                return ResourceManager.GetString("InPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intermediate data ähnelt.
        /// </summary>
        internal static string IntermediateText {
            get {
                return ResourceManager.GetString("IntermediateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Keys ähnelt.
        /// </summary>
        internal static string LoadKeysTitle {
            get {
                return ResourceManager.GetString("LoadKeysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string MenuInfo {
            get {
                return ResourceManager.GetString("MenuInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not allowed in BIN-Modus ähnelt.
        /// </summary>
        internal static string NotBin {
            get {
                return ResourceManager.GetString("NotBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not allowed in HEX-Modus ähnelt.
        /// </summary>
        internal static string NotHex {
            get {
                return ResourceManager.GetString("NotHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This funtion is not available yet!  In future you can buy the funtionality in the Marketplace Dialog ähnelt.
        /// </summary>
        internal static string NotLight {
            get {
                return ResourceManager.GetString("NotLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This funtion is not available in the trail version  ähnelt.
        /// </summary>
        internal static string NotTrail {
            get {
                return ResourceManager.GetString("NotTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, this function in not implemented yet ähnelt.
        /// </summary>
        internal static string NotYet {
            get {
                return ResourceManager.GetString("NotYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This function requires UPN mode ähnelt.
        /// </summary>
        internal static string OnlyUpn {
            get {
                return ResourceManager.GetString("OnlyUpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load  and save all register  key-assignments and  programs ähnelt.
        /// </summary>
        internal static string OptionPersistence {
            get {
                return ResourceManager.GetString("OptionPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load key-assignments from and save to  files  ähnelt.
        /// </summary>
        internal static string OptionPersistence1 {
            get {
                return ResourceManager.GetString("OptionPersistence1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows a list of all entered values and commands and all calculation results. ähnelt.
        /// </summary>
        internal static string OptionPrinter {
            get {
                return ResourceManager.GetString("OptionPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The List can be cleared or stored as file ähnelt.
        /// </summary>
        internal static string OptionPrinter1 {
            get {
                return ResourceManager.GetString("OptionPrinter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load programs from text file and execute them. ähnelt.
        /// </summary>
        internal static string OptionProgramming {
            get {
                return ResourceManager.GetString("OptionProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die handle up to 99 data series of different length ähnelt.
        /// </summary>
        internal static string OptionRobustStatistic {
            get {
                return ResourceManager.GetString("OptionRobustStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die use median and MAD ähnelt.
        /// </summary>
        internal static string OptionRobustStatistic1 {
            get {
                return ResourceManager.GetString("OptionRobustStatistic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die perform t and f test and remove outliers ähnelt.
        /// </summary>
        internal static string OptionRobustStatistic2 {
            get {
                return ResourceManager.GetString("OptionRobustStatistic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use the original statistic funtion ähnelt.
        /// </summary>
        internal static string OptionStatistic {
            get {
                return ResourceManager.GetString("OptionStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        internal static string ResultText {
            get {
                return ResourceManager.GetString("ResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Keys ähnelt.
        /// </summary>
        internal static string SaveKeysTitle {
            get {
                return ResourceManager.GetString("SaveKeysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display ähnelt.
        /// </summary>
        internal static string UPNCourseDisplay {
            get {
                return ResourceManager.GetString("UPNCourseDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keys ähnelt.
        /// </summary>
        internal static string UPNCourseKey {
            get {
                return ResourceManager.GetString("UPNCourseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remark ähnelt.
        /// </summary>
        internal static string UPNCourseRemark {
            get {
                return ResourceManager.GetString("UPNCourseRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short UPN course ähnelt.
        /// </summary>
        internal static string UPNCourseTitle {
            get {
                return ResourceManager.GetString("UPNCourseTitle", resourceCulture);
            }
        }
    }
}
